# ---- Production Stage ----
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# ติดตั้ง sharp
RUN npm install sharp

# คัดลอกไฟล์ที่ build แล้วจาก builder
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next/standalone ./standalone
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

# ใช้ standalone server
CMD ["node", "standalone/server.js"]
