version: "3.9"

services:
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
    command:
      - "--address=0.0.0.0"
      - "--port=3306"
      # หากใช้ Private IP ค่อยเพิ่ม --private-ip
      - "webbank-470204:asia-southeast1:base-mysql"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.prod
    depends_on:
      - cloud-sql-proxy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3001/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "https://api-crm.cropsciences.co.th"
    env_file:
      - ./frontend/.env.prod
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: always

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ops/nginx/conf.d:/etc/nginx/conf.d:ro
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
    entrypoint: /bin/sh
    command: -c "while :; do certbot renew --webroot -w /var/www/certbot --deploy-hook 'nginx -s reload'; sleep 12h; done"
    restart: always

volumes:
  certs:
  webroot:
