version: '3.8'

services:
  db-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
    command:
      - "--structured-logs"
      - "--port=3306"
      - "webprojectbank:asia-southeast1:crm-mysql-instance" # <-- แก้ไขตรงนี้
    restart: always
    networks:
      - crm-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db-proxy
    ports:
      - "3001:8080" # Map port 8080 inside container to 3001 on VM
    environment:
      # DATABASE_URL now points to the proxy service
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@db-proxy:3306/${DB_NAME}"
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      PORT: 8080 # Tell the app to listen on port 8080
    networks:
      - crm-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Frontend talks to backend via its service name on the Docker network
      NEXT_PUBLIC_API_URL: http://backend:8080
    depends_on:
      - backend
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge