version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: crm_db_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_prod:/var/lib/mysql
    networks:
      - crm-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm_backend_prod
    restart: always
    depends_on:
      - db
    ports:
      - "3001:8080"
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}"
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      PORT: 8080
    networks:
      - crm-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crm_frontend_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      # This URL is used by the user's browser to talk to the backend.
      # It must be the public IP of your VM.
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - crm-network

volumes:
  db_data_prod:

networks:
  crm-network:
    driver: bridge
