# === DEVELOPMENT ENVIRONMENT ===
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: crm_backend_dev
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npx prisma generate && npm run start:dev"
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@host.docker.internal:3306/${DB_NAME}"
      SHADOW_DATABASE_URL: "mysql://root:${DB_ROOT_PASSWORD}@host.docker.internal:3306/prisma_shadow"
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    networks:
      - crm-network-dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: crm_frontend_dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - crm-network-dev

networks:
  crm-network-dev:
    driver: bridge
