# This file is specifically for development and overrides the base docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma generate && npm run start:dev"
    environment:
      # This enables polling mode, which is a reliable way to detect file changes in Docker.
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      # This enables polling mode for Next.js hot reloading.
      - CHOKIDAR_USEPOLLING=true
