# === DEVELOPMENT ENVIRONMENT ===
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: crm_db_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
    # --- ADDED HEALTHCHECK ---
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm-network-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: crm_backend_dev
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma generate && npm run start:dev"
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}"
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    # --- UPDATED depends_on ---
    depends_on:
      db:
        condition: service_healthy
    networks:
      - crm-network-dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: crm_frontend_dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - crm-network-dev

volumes:
  db_data_dev:

networks:
  crm-network-dev:
    driver: bridge